[build]
builder = "DOCKERFILE"
dockerfilePath = "deploy/relay/relay.Dockerfile"

[deploy]
healthcheckPath = "/healthz"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
